name: create-issue

on:
   deployment_status:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/github-script@v7
        if: github.event.deployment_status.state == 'failure'
        id: list-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            var exists
            for (const issue of issues.data) {
               for (const label of issue.labels){
                  if (label.name == 'incident'){
                     exists = true
                  }
               }
            }
            if (!exists) {
               const issue = await github.rest.issues.create({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 title: "deployment failed",
                 labels: ["incident"],
            })
            }
      - uses: actions/github-script@v7
        if: github.event.deployment_status.state == 'success'
        id: close-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            var exists
            var issueNumber
            for (const issue of issues.data) {
               for (const label of issue.labels){
                  if (label.name == 'incident'){
                     exists = true
                     issueNumber = issue.number
                  }
               }
            }
            if (exists) {
               const issue = await github.rest.issues.update({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 issue_number: issueNumber,
                 state: "closed"
            })
            }
            

